// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/1/2026, 9:13:52 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/earth/Documents/MyApp/ChangeStreams/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/earth/Documents/MyApp/ChangeStreams/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/earth/Documents/MyApp/ChangeStreams/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/earth/Documents/MyApp/ChangeStreams/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/earth/Documents/MyApp/ChangeStreams/frontend/plugins/**/*.{js,ts,mjs}","/Users/earth/Documents/MyApp/ChangeStreams/frontend/composables/**/*.{js,ts,mjs}","/Users/earth/Documents/MyApp/ChangeStreams/frontend/utils/**/*.{js,ts,mjs}","/Users/earth/Documents/MyApp/ChangeStreams/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/earth/Documents/MyApp/ChangeStreams/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/earth/Documents/MyApp/ChangeStreams/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/earth/Documents/MyApp/ChangeStreams/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;